### PR TITLE
Improve npm scripts

### PR DESCRIPTION
**Pull request by operatino**
Allow running npm scripts without global coffee, add regular build commands.

### CODE REVIEW

**Comment by sakren** [comment]
Thanks for this update, but please can you change indentation back to tabs?

**Comment by operatino** [comment]
I could change it, but this is what npm does by default if you use something like `--save` for example. It will always break after any npm manipulation. Maybe it's better to keep compatible with it? Or you want to have your own custom formating?

**Comment by operatino** [comment]
Maybe we should also bump CoffeeScript version to latest 1.9.x? Or it's better to keep the current one, with which you built project before `1.6.3`?

**Comment by sakren** [comment]
It seems that it should be possible to set indentation with .editorconfig, see npm/npm#6600 which would be really great. But I'll do that myself if you don't mind :-)

Also I always update all dependencies before publishing new version so if you'll do that instead of me, I'll be really grateful.

**Comment by operatino** [comment]
Ok, so just add coffee-script as devDependency and update npm scripts as proposed (or your way).

**Comment by sakren** [comment]
That would be great and you can just force push it here

**Pull request closed without merging**
