### PR TITLE
fix `expandPath` on windows

### PR DESCRIPTION
**Pull request by operatino**
fix `expandPath` on windows #9

### CODE REVIEW

**Comment by sakren** [comment]
Thank you sir and sorry that I didn't reply to your issue sooner..

**Comment by szarouski** [comment]
Hi @sakren, thank you for merging this one. Are you planning to publish it soon?

**Comment by operatino** [comment]
@szarouski If you're asking about @sourcejs dep, I'm now using there version from my fork, so it's stable in 0.5.3-dev. I'm planning release today/tomorrow, after filling some docs.

**Comment by sakren** [comment]
And if you're asking for this package, I'm planning to release new version hopefully in a few days. There are some issues which I forgot...

Btw @sourcejs looks pretty good  ;-)

**Comment by operatino** [comment]
@davidkudera, seems like my fix isn't released yet, and it doesn't appear in master, could you please re-check it?

**Pull request merged**
